version: '3.7'
services:
  animal-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/lifestock
  schedule-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/lifestock
  health-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/lifestock
  mongo:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
